#!/usr/bin/env bash

### aliases
## git
alias g="git status"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit"
alias gb="git branch"
alias gbd="git branch -d"
alias gch="git checkout"
alias gd="git diff"
alias gp="git push"
alias gl="git pull"

## files
alias ll="ls -la"
alias v=vim

### Environment variables
export LANG=en_US
export TERM=xterm-256color
export HISTCONTROL=ignoreboth:erasedups
ENV_VAR_FILE=~/.bash-kit/env-var.sh
if [ -f $ENV_VAR_FILE ];
then
    source $ENV_VAR_FILE
else
    echo "$ENV_VAR_FILE doesn't exist, you can create it to define env vars."
fi
