" To use Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" My Bundles here
Bundle 'gmarik/Vundle.vim'
Bundle 'taglist.vim'
Bundle 'jiangmiao/auto-pairs'
Bundle 'ervandew/supertab'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" keep more context when scrolling off
set scrolloff=5

" Join lines
set nojoinspaces

" language syntax
syntax on

" colorscheme
colorscheme desert

" line number
set number

" ruler
set ruler

" auto change directory
set autochdir

" searching
set ignorecase smartcase 
set incsearch
set hlsearch

" indentation and tab
set smartindent
set backspace=indent,eol,start
au FileType python setl sw=4 sts=4 et
au FileType xml setl sw=2 sts=2 et
au FileType fortran setl sw=2 sts=2 et
nnoremap <leader>2 :set tabstop=2 softtabstop=2 shiftwidth=2<CR>
nnoremap <leader>4 :set tabstop=4 softtabstop=4 shiftwidth=4<CR>

" leader key bindings, timeout and escape
autocmd InsertEnter * set timeoutlen=100
autocmd InsertLeave * set timeoutlen=1000
let mapleader=" "
nnoremap <leader>ss :w<cr>
nnoremap <leader>noh :noh<cr>
inoremap jk <esc>
inoremap kj <esc>

" tags and taglist
set tags=./tags;/
nnoremap <leader>tl :TlistToggle<cr>
let Tlist_Show_One_File=0
let Tlist_Exit_OnlyWindow=1
let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1

" fold
set foldmethod=indent
set foldlevel=99

" grep
function VimGrepWord()
  let w = expand("<cword>")
  execute "vimgrep " . w . " **"
endfunction
nnoremap <leader>gr :call VimGrepWord()<CR>:copen<CR>
